#!/usr/bin/env python3
"""Generate dlssnr_extract_tables.hpp for dlssnr_extract_model.cpp.

Embeds what the Python model tools read from disk at run time:

  descriptor.json     each layer's (block, layer) key, type and channel counts,
                      resolved as the unpackers resolve them (a dict keyed by
                      (block index, layer index); a later duplicate wins)
  model-files.txt     the packed entries, in order, parsed as pack_model.py does
  model-files.sha256  the expected sha256 per entry, parsed as pack_model.py
                      --verify does (a later duplicate wins), plus any names
                      it lists that model-files.txt does not (pack fails on them)

    gen_extract_tables.py --descriptor D --list L --sums S --out H

Defaults are linux/package/model-tools/'s files, relative to the repository root.
"""
import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
# The C++ program produces exactly these families (inspect_nr.py --extract's
# weights/ and the five unpackers' output directories).
PREFIXES = ("inventory/weights/", "unpacked/", "unpacked-splitswin/", "unpacked-vit/",
            "unpacked-preblock/", "unpacked-postblock/")
SAFE = re.compile(r"[A-Za-z0-9_.-]+")


def cstr(s):
    assert all(0x20 <= ord(c) < 0x7f and c not in '"\\' for c in s), s
    return '"%s"' % s


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--descriptor", type=Path, default=ROOT / "linux/package/model-tools/descriptor.json")
    ap.add_argument("--list", type=Path, default=ROOT / "linux/package/model-tools/model-files.txt")
    ap.add_argument("--sums", type=Path, default=ROOT / "linux/package/model-tools/model-files.sha256")
    ap.add_argument("--out", type=Path,
                    default=ROOT / "windows/package/model-tools/dlssnr_extract_tables.hpp")
    a = ap.parse_args()

    # As the unpackers: {(b["index"], l["index"]): l for b in blocks for l in b["layers"]}.
    graph = json.loads(a.descriptor.read_text())
    layers = {(b["index"], l["index"]): l for b in graph["blocks"] for l in b["layers"]}
    types, rows = [], []
    for (bi, li), l in layers.items():
        ci, co, t = l["input_channels"], l["output_channels"], l["type"]
        for v in (bi, li, ci, co):
            assert type(v) is int and 0 <= v < 2**31, (bi, li, v)
        if t not in types:
            types.append(t)
        rows.append((bi, li, types.index(t), ci, co))

    # As pack_model.py.
    names = [l.strip() for l in a.list.read_text().splitlines()
             if l.strip() and not l.startswith("#")]
    want = {}
    for line in a.sums.read_text().splitlines():
        if line.strip():
            h, n = line.split(None, 1)
            want[n.strip()] = h
    listed = set(names)
    extra = [n for n in want if n not in listed]

    # Exact-string lookup in the C++ program must equal path lookup in Python.
    for n in names:
        assert n.startswith(PREFIXES), "entry outside the produced families: " + n
        parts = n.split("/")
        assert all(SAFE.fullmatch(p) and p not in (".", "..") for p in parts), n
        assert n.count("/") == (2 if n.startswith("inventory/") else 1), n
        assert n.endswith(".bin"), n

    out = ["// Generated by gen_extract_tables.py - do not edit.",
           "// descriptor: %s" % a.descriptor.name,
           "// list: %s (%d entries)" % (a.list.name, len(names)),
           "// sums: %s" % a.sums.name,
           "#pragma once",
           "namespace tables {",
           "struct Layer { int block, layer, type, in, out; };",
           "static const char* const kTypes[] = {"]
    out += ["    %s," % cstr(t) for t in types]
    out += ["};", "static const Layer kLayers[] = {"]
    out += ["    {%d, %d, %d, %d, %d}," % r for r in rows]
    out += ["};", "static const unsigned kLayerCount = %d;" % len(rows),
            "// Entry name and expected sha256 (\"\" when model-files.sha256 lacks it).",
            "struct Entry { const char* name; const char* sha256; };",
            "static const Entry kEntries[] = {"]
    out += ["    {%s, %s}," % (cstr(n), cstr(want.get(n, ""))) for n in names]
    out += ["};", "static const unsigned kEntryCount = %d;" % len(names),
            "// Names in model-files.sha256 that model-files.txt lacks.",
            "static const char* const kVerifyExtra[] = {"]
    out += ["    %s," % cstr(n) for n in extra]
    out += ["    nullptr,", "};", "}  // namespace tables", ""]
    a.out.write_text("\n".join(out))
    print("%s: %d layers, %d types, %d entries, %d extra sums"
          % (a.out, len(rows), len(types), len(names), len(extra)))


if __name__ == "__main__":
    main()
