// Copyright (c) 2026 Mauri de Souza Meneguzzo (mauri870). MIT, see LICENSE.
// DlssnrAmdRuntime.dll: this project's network as a neural runtime for AMDNR's OptiScaler.
//
// AMDNR's host (https://github.com/3zwr1/AMD-NR---OptiScaler, dlssnr/lmxxf/LmxxfBackend.cpp) feeds a
// neural runtime an encoded FP16 proxy of the frame at the network's size (and, for history, a
// motion image), and later takes the network's answer back as an FP16 texture; it forms the edit
// itself (answer minus what the network was fed). That contract is the C ABI in nr_amdnr_abi.hpp,
// exported under the names the host looks up.
//
// This file is the ABI: it checks what the host sends, keeps each job's state, and hands the work to
// a transport (nr_amdnr_transport.hpp) - the network recorded into the host's own command list when
// the D3D12 device is vkd3d-proton, or run on a Vulkan device of our own beside the host's otherwise.

#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <d3d12.h>

#include "nr_amdnr_abi.hpp"
#include "nr_amdnr_transport.hpp"
#include "nr_pe_log.hpp"

#include <algorithm>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <memory>
#include <mutex>
#include <string>
#include <utility>
#include <vector>

extern "C" void nr_vk_load(void);   // generated by the build; see linux/build/build_amdnr_runtime.sh

using nr::pe::log;
using nr::amdnr::Result;

namespace {

constexpr uint32_t kMaxExtent = 4096;
// Frame-info sizes a host has sent over the ABI's life; anything else is a different struct.
constexpr uint32_t kFrameInfoSizes[] = {64, 88, 120, 128, 144};

std::mutex g_lock;
std::string g_last_error;

int32_t fail(int32_t code, std::string message) {
    g_last_error = std::move(message);
    log("[amdnr] %s", g_last_error.c_str());
    return code;
}

int32_t code_of(Result r) {
    switch (r) {
        case Result::Ok: return NR_ABI_OK;
        case Result::Unavailable: return NR_ABI_UNAVAILABLE;
        default: return NR_ABI_FAILED;
    }
}

struct JobEntry {
    uint32_t state = NR_ABI_JOB_NONE;
    std::unique_ptr<nr::amdnr::Job> job;
};

struct Context {
    std::unique_ptr<nr::amdnr::Transport> transport;
    std::vector<std::unique_ptr<JobEntry>> jobs;
    uint64_t answers = 0;
    bool logged_strength = false, logged_passes = false;
    uint32_t width = 0, height = 0;   // of the last frame
};

Context* as_context(void* p) { return static_cast<Context*>(p); }
JobEntry* find_job(Context* c, void* handle) {
    for (auto& j : c->jobs)
        if (j.get() == handle) return j.get();
    return nullptr;
}

void remove_job(Context& c, JobEntry* entry, bool wait) {
    for (auto it = c.jobs.begin(); it != c.jobs.end(); ++it) {
        if (it->get() != entry) continue;
        if (entry->job) c.transport->finish(std::move(entry->job), wait);
        c.jobs.erase(it);
        return;
    }
}

// ---------------------------------------------------------------------------------------------
// The table.
// ---------------------------------------------------------------------------------------------

int32_t QueryCapabilities(NrAbiCapabilities* out) {
    if (!out) return NR_ABI_INVALID_ARGUMENT;
    std::memset(out, 0, sizeof *out);
    out->struct_size = sizeof *out;
    out->abi_version = NR_ABI_VERSION;
    out->max_input_width = kMaxExtent;
    out->max_input_height = kMaxExtent;
    out->history_supported = 1;
    out->hip_ready = 1;
    return NR_ABI_OK;
}

int32_t Create(const NrAbiCreateInfo* info, void** context) {
    std::lock_guard<std::mutex> guard(g_lock);
    if (!info || !context || !info->device || !info->queue) return fail(NR_ABI_INVALID_ARGUMENT, "Create: no device or queue");
    if (info->flags != 0) return fail(NR_ABI_INVALID_ARGUMENT, "Create: unknown flags");
    auto* device = static_cast<ID3D12Device*>(info->device);
    auto* queue = static_cast<ID3D12CommandQueue*>(info->queue);

    // DLSSNR_AMD_TRANSPORT=inline|native forces one; otherwise the inline transport where the device is
    // vkd3d-proton and the native one on the system's D3D12.
    char forced[16] = {};
    GetEnvironmentVariableA("DLSSNR_AMD_TRANSPORT", forced, sizeof forced);
    std::string why_inline, why_native;
    std::unique_ptr<nr::amdnr::Transport> transport;
    if (!std::strcmp(forced, "native")) why_inline = "not tried (DLSSNR_AMD_TRANSPORT=native)";
    else transport = nr::amdnr::make_inline_transport(device, queue, &why_inline);
    if (!transport && std::strcmp(forced, "inline"))
        transport = nr::amdnr::make_native_transport(device, queue, &why_native);
    if (!transport)
        return fail(NR_ABI_UNAVAILABLE, "Create: no transport can run on this device. inline: " + why_inline +
                                            (why_native.empty() ? std::string() : "; native: " + why_native));
    auto c = std::make_unique<Context>();
    log("[amdnr] runtime created, %s transport", transport->name());
    c->transport = std::move(transport);
    g_last_error.clear();
    *context = c.release();
    return NR_ABI_OK;
}

int32_t Destroy(void* context) {
    std::lock_guard<std::mutex> guard(g_lock);
    if (!context) return NR_ABI_INVALID_ARGUMENT;
    auto* c = as_context(context);
    c->transport->drain();
    for (auto& j : c->jobs)
        if (j->job) c->transport->finish(std::move(j->job), true);
    c->jobs.clear();
    delete c;
    return NR_ABI_OK;
}

int32_t PrepareSession(void* context) {
    std::lock_guard<std::mutex> guard(g_lock);
    return context ? NR_ABI_OK : NR_ABI_INVALID_ARGUMENT;
}

int32_t PrepareFrame(void* context, const NrAbiFrameInfo* info, NrAbiJob* job) {
    std::lock_guard<std::mutex> guard(g_lock);
    if (!context || !info || !job) return fail(NR_ABI_INVALID_ARGUMENT, "PrepareFrame: null argument");
    auto& c = *as_context(context);
    bool size_ok = false;
    for (uint32_t s : kFrameInfoSizes) size_ok |= info->struct_size == s;
    if (!size_ok) return fail(NR_ABI_INVALID_ARGUMENT, "PrepareFrame: struct_size mismatch");
    // Fields past the size the host sent read as zero.
    NrAbiFrameInfo f{};
    std::memcpy(&f, info, std::min<size_t>(info->struct_size, sizeof f));
    if (f.flags & ~uint32_t(NR_ABI_FRAME_KNOWN_FLAGS)) return fail(NR_ABI_INVALID_ARGUMENT, "PrepareFrame: unknown flags");
    if ((f.flags & NR_ABI_FRAME_CONTROLS) && info->struct_size != sizeof(NrAbiFrameInfo))
        return fail(NR_ABI_INVALID_ARGUMENT, "PrepareFrame: controls need struct_size 144");
    if (!f.command_list || !f.color) return fail(NR_ABI_INVALID_ARGUMENT, "PrepareFrame: no command list or colour");
    if (!f.color_width || !f.color_height || f.color_width > kMaxExtent || f.color_height > kMaxExtent)
        return fail(NR_ABI_INVALID_ARGUMENT, "PrepareFrame: colour size out of range");

    nr::amdnr::FrameRequest request;
    if (f.flags & NR_ABI_FRAME_CONTROLS) {
        const float values[] = {f.control_tone, f.control_structure, f.control_skin, f.control_other, f.control_style};
        for (float v : values)
            if (!(v >= -1.0f && v <= 4.0f)) return fail(NR_ABI_INVALID_ARGUMENT, "PrepareFrame: control out of range");
        request.controls.local_tone = f.control_tone;
        request.controls.local_structure = f.control_structure;
        request.controls.skin_structure = f.control_skin;
    }
    if (!c.logged_strength && (f.flags & NR_ABI_FRAME_STRENGTH) && (f.transfer_strength < 1.0f || f.color_strength < 1.0f)) {
        c.logged_strength = true;
        log("[amdnr] Detail / Colour strength below 1 are the host's to apply; the answer is the network's own");
    }
    if (!c.logged_passes && f.passes > 1) {
        c.logged_passes = true;
        log("[amdnr] %u network passes asked for; this runtime runs one", f.passes);
    }

    request.list = static_cast<ID3D12GraphicsCommandList*>(f.command_list);
    request.colour = static_cast<ID3D12Resource*>(f.color);
    request.colour_state = static_cast<D3D12_RESOURCE_STATES>(f.color_state);
    request.width = f.color_width;
    request.height = f.color_height;
    const bool temporal = (f.flags & NR_ABI_FRAME_TEMPORAL) && f.motion;
    if (temporal) {
        request.motion = static_cast<ID3D12Resource*>(f.motion);
        request.motion_state = static_cast<D3D12_RESOURCE_STATES>(f.motion_state);
        request.motion_width = f.motion_width ? f.motion_width : f.color_width;
        request.motion_height = f.motion_height ? f.motion_height : f.color_height;
        request.motion_scale_x = f.motion_scale_x;
        request.motion_scale_y = f.motion_scale_y;
    }
    // Without the temporal flag the host asked for no history at all.
    request.reset = f.history_reset != 0 || !temporal;

    std::unique_ptr<nr::amdnr::Job> made;
    std::string why;
    const Result r = c.transport->prepare(request, &made, &why);
    if (r != Result::Ok) return fail(code_of(r), "PrepareFrame: " + why);
    auto entry = std::make_unique<JobEntry>();
    entry->state = NR_ABI_JOB_PREPARED;
    entry->job = std::move(made);
    c.width = f.color_width;
    c.height = f.color_height;
    job->handle = entry.get();
    job->private_output = entry->job->output();
    c.jobs.push_back(std::move(entry));
    g_last_error.clear();
    return NR_ABI_OK;
}

int32_t RecordInputs(void* context, void* handle, void* command_list) {
    std::lock_guard<std::mutex> guard(g_lock);
    if (!context || !handle || !command_list) return fail(NR_ABI_INVALID_ARGUMENT, "RecordInputs: null argument");
    auto& c = *as_context(context);
    JobEntry* entry = find_job(&c, handle);
    if (!entry) return fail(NR_ABI_INVALID_ARGUMENT, "RecordInputs: unknown job");
    if (entry->state != NR_ABI_JOB_PREPARED) return fail(NR_ABI_INVALID_ARGUMENT, "RecordInputs: job is not prepared");
    std::string why;
    const Result r = c.transport->record_inputs(*entry->job, static_cast<ID3D12GraphicsCommandList*>(command_list), &why);
    if (r != Result::Ok) return fail(code_of(r), "RecordInputs: " + why);
    entry->state = NR_ABI_JOB_PRODUCER_SUBMITTED;
    g_last_error.clear();
    return NR_ABI_OK;
}

int32_t Enqueue(void* context, void* handle, void* queue) {
    std::lock_guard<std::mutex> guard(g_lock);
    if (!context || !handle || !queue) return fail(NR_ABI_INVALID_ARGUMENT, "EnqueueHip: null argument");
    auto& c = *as_context(context);
    JobEntry* entry = find_job(&c, handle);
    if (!entry) return fail(NR_ABI_INVALID_ARGUMENT, "EnqueueHip: unknown job");
    if (entry->state != NR_ABI_JOB_PRODUCER_SUBMITTED) return fail(NR_ABI_INVALID_ARGUMENT, "EnqueueHip: inputs were not recorded");
    std::string why;
    const Result r = c.transport->launch(*entry->job, static_cast<ID3D12CommandQueue*>(queue), &why);
    if (r != Result::Ok) return fail(code_of(r), "EnqueueHip: " + why);
    entry->state = NR_ABI_JOB_NR_ENQUEUED;
    return NR_ABI_OK;
}

int32_t RecordOutputs(void* context, void* handle, void* command_list) {
    std::lock_guard<std::mutex> guard(g_lock);
    if (!context || !handle || !command_list) return fail(NR_ABI_INVALID_ARGUMENT, "RecordOutputs: null argument");
    auto& c = *as_context(context);
    JobEntry* entry = find_job(&c, handle);
    if (!entry) return fail(NR_ABI_INVALID_ARGUMENT, "RecordOutputs: unknown job");
    if (entry->state != NR_ABI_JOB_NR_ENQUEUED && entry->state != NR_ABI_JOB_NR_COMPLETE)
        return fail(NR_ABI_INVALID_ARGUMENT, "RecordOutputs: the job was not launched");
    std::string why;
    const Result r = c.transport->record_outputs(*entry->job, static_cast<ID3D12GraphicsCommandList*>(command_list), &why);
    if (r != Result::Ok) return fail(code_of(r), "RecordOutputs: " + why);
    entry->state = NR_ABI_JOB_CONSUMER_COMPLETE;
    ++c.answers;
    return NR_ABI_OK;
}

int32_t ExecuteAfterProducer(void* context, void* handle, void* queue) {
    return context && handle && queue ? NR_ABI_OK : NR_ABI_INVALID_ARGUMENT;
}

int32_t CancelUnsubmitted(void* context, void* handle) {
    std::lock_guard<std::mutex> guard(g_lock);
    if (!context || !handle) return NR_ABI_INVALID_ARGUMENT;
    auto& c = *as_context(context);
    JobEntry* entry = find_job(&c, handle);
    if (!entry) return NR_ABI_INVALID_ARGUMENT;
    remove_job(c, entry, false);
    return NR_ABI_OK;
}

int32_t Poll(void* context, void* handle, uint32_t* state) {
    std::lock_guard<std::mutex> guard(g_lock);
    if (!context || !handle || !state) return NR_ABI_INVALID_ARGUMENT;
    auto& c = *as_context(context);
    JobEntry* entry = find_job(&c, handle);
    if (!entry) return NR_ABI_INVALID_ARGUMENT;
    if (entry->state == NR_ABI_JOB_NR_ENQUEUED && c.transport->ready(*entry->job)) entry->state = NR_ABI_JOB_NR_COMPLETE;
    *state = entry->state;
    return NR_ABI_OK;
}

// A job whose answer was consumed: nothing of it is in flight.
int32_t Retire(void* context, void* handle) {
    std::lock_guard<std::mutex> guard(g_lock);
    if (!context || !handle) return NR_ABI_INVALID_ARGUMENT;
    auto& c = *as_context(context);
    JobEntry* entry = find_job(&c, handle);
    if (!entry) return NR_ABI_INVALID_ARGUMENT;
    remove_job(c, entry, false);
    return NR_ABI_OK;
}

// A launched job given up before its answer was consumed: its work completes on the CPU first.
int32_t AbandonJob(void* context, void* handle) {
    std::lock_guard<std::mutex> guard(g_lock);
    if (!context || !handle) return NR_ABI_INVALID_ARGUMENT;
    auto& c = *as_context(context);
    JobEntry* entry = find_job(&c, handle);
    if (!entry) return NR_ABI_INVALID_ARGUMENT;
    remove_job(c, entry, true);
    return NR_ABI_OK;
}

int32_t ResetHistory(void* context) {
    std::lock_guard<std::mutex> guard(g_lock);
    if (!context) return NR_ABI_INVALID_ARGUMENT;
    as_context(context)->transport->reset_history();
    return NR_ABI_OK;
}

int32_t Drain(void* context) {
    std::lock_guard<std::mutex> guard(g_lock);
    if (!context) return NR_ABI_INVALID_ARGUMENT;
    as_context(context)->transport->drain();
    return NR_ABI_OK;
}

int32_t OutputReady(void* context, void* handle, uint32_t* ready) {
    std::lock_guard<std::mutex> guard(g_lock);
    if (!context || !handle || !ready) return NR_ABI_INVALID_ARGUMENT;
    auto& c = *as_context(context);
    JobEntry* entry = find_job(&c, handle);
    if (!entry) return NR_ABI_INVALID_ARGUMENT;
    *ready = c.transport->ready(*entry->job) ? 1 : 0;
    return NR_ABI_OK;
}

int32_t copy_text(const std::string& text, char* buffer, uint32_t chars) {
    if (!buffer || !chars) return NR_ABI_INVALID_ARGUMENT;
    std::snprintf(buffer, chars, "%s", text.c_str());
    return NR_ABI_OK;
}

// The host reads words out of this: hip_ms= (network time), hist= (history state), skip= (block
// schedule). This network always runs every block.
int32_t GetStatus(void* context, char* buffer, uint32_t chars) {
    std::lock_guard<std::mutex> guard(g_lock);
    if (!context) return NR_ABI_INVALID_ARGUMENT;
    auto& c = *as_context(context);
    char text[256];
    std::snprintf(text, sizeof text, "dlssnr-amd %s %ux%u hip_ms=%.2f hist=on/%llu skip=none answers=%llu",
                  c.transport->name(), c.width, c.height, double(c.transport->gpu_ms()), (unsigned long long)c.answers,
                  (unsigned long long)c.answers);
    g_last_error.clear();
    return copy_text(text, buffer, chars);
}

int32_t GetLastError(char* buffer, uint32_t chars) {
    std::lock_guard<std::mutex> guard(g_lock);
    return copy_text(g_last_error, buffer, chars);
}

}  // namespace

extern "C" {

__declspec(dllexport) int32_t LmxxfNrGetApi(uint32_t abi_version, NrAbiApi* out) {
    if (!out || out->struct_size < sizeof(NrAbiApi)) return NR_ABI_INVALID_ARGUMENT;
    if (abi_version != NR_ABI_VERSION) return NR_ABI_UNSUPPORTED_ABI;
    NrAbiApi api{};
    api.struct_size = sizeof api;
    api.abi_version = NR_ABI_VERSION;
    api.QueryCapabilities = QueryCapabilities;
    api.Create = Create;
    api.Destroy = Destroy;
    api.PrepareSession = PrepareSession;
    api.PrepareFrame = PrepareFrame;
    api.RecordInputs = RecordInputs;
    api.EnqueueHip = Enqueue;
    api.RecordOutputs = RecordOutputs;
    api.ExecuteAfterProducer = ExecuteAfterProducer;
    api.CancelUnsubmitted = CancelUnsubmitted;
    api.Poll = Poll;
    api.Retire = Retire;
    api.ResetHistory = ResetHistory;
    api.Drain = Drain;
    api.GetStatus = GetStatus;
    api.GetLastError = GetLastError;
    api.EnqueueHipAsync = Enqueue;
    api.AbandonJob = AbandonJob;
    api.OutputReady = OutputReady;
    *out = api;
    return NR_ABI_OK;
}

// The host looks for this one to learn whether the runtime reuses its shared buffers. This runtime
// keeps its buffers for as long as a frame size lasts, so reuse is on.
__declspec(dllexport) int32_t LmxxfNrGetImportPoolStats(NrAbiImportPoolStats* out) {
    if (!out) return NR_ABI_INVALID_ARGUMENT;
    std::memset(out, 0, sizeof *out);
    out->struct_size = sizeof *out;
    out->enabled = 1;
    return NR_ABI_OK;
}

// Network size tiers are not a notion of this network; bit 0 is the only bit the host may set.
__declspec(dllexport) int32_t LmxxfNrSetTierPolicy(void* context, uint32_t flags) {
    if (!context || (flags & ~1u)) return NR_ABI_INVALID_ARGUMENT;
    return NR_ABI_OK;
}

BOOL APIENTRY DllMain(HMODULE module, DWORD reason, LPVOID) {
    if (reason == DLL_PROCESS_ATTACH) {
        DisableThreadLibraryCalls(module);
        nr::pe::set_module(module);
        nr_vk_load();
#ifndef NR_BUILD_STAMP
#define NR_BUILD_STAMP "unstamped"
#endif
        nr::pe::log("[amdnr] attached (build %s, %s %s), log %s", NR_BUILD_STAMP, __DATE__, __TIME__, nr::pe::log_path());
    }
    return TRUE;
}

}  // extern "C"
