// nvngx.dll_dlssnr.dll for AMD: the exports OptiScaler's DLSS-NR forks drive the model through,
// backed by our own network instead of NVIDIA's snippet.
//
// 28 of them: the 25 Dagherbou's OptiScaler_DLSSNR publishes, plus the three the pre-SR fork added --
// dlssnr_call_evaluate_v2, dlssnr_vk_evaluate_v2 (per-resource subrects, so depth and motion may be at
// a different resolution from colour) and dlssnr_call_error (why the model declined, in words). The
// fork resolves ONLY the v2 names and refuses to run without them; the v1 pair is kept because there
// are hosts that still drive it.
//
// This file is now only the ABI. The model behind it -- the sessions, the features, the history rule,
// the seed copy and the control mapping -- is linux/src/pe/nr_dlssnr_model.cpp, shared with _nvngx.dll,
// which reaches the same model through NVSDK_NGX_D3D12_CreateFeature(18). wilsjo2's fork from 0.8.1 on
// loads no forwarder at all and uses that door instead; Dagherbou's release uses this one.
//
// OptiScaler is not modified. It loads "nvngx.dll_dlssnr.dll" from beside itself or the executable,
// resolves the exports below by name, and drives them exactly as it drives NVIDIA's. Everything about
// the call sequence, the argument order and the return conventions was read from, and must keep
// matching:
//
//   OptiScaler_DLSSNR/OptiScaler/dlssnr/forwarder/dlssnr_forwarder.cpp   (the ABI)
//   OptiScaler_DLSSNR/OptiScaler/shaders/dlssnr/DlssNr_Dx12.cpp          (the D3D12 caller)
//   OptiScaler_DLSSNR/OptiScaler/dlssnr/DlssNrFeature_Vk.cpp             (the Vulkan caller)
//
// and for the v2 surface:
//
//   artifacts/ref/wilsjo2-OptiScaler-DLSSNR-PreSR-Multipass/OptiScaler/dlssnr/forwarder/dlssnr_forwarder.cpp
//   artifacts/ref/wilsjo2-OptiScaler-DLSSNR-PreSR-Multipass/OptiScaler/shaders/dlssnr/DlssNr_Dx12.cpp
//   artifacts/ref/wilsjo2-OptiScaler-DLSSNR-PreSR-Multipass/OptiScaler/shaders/dlssnr/DlssNr_Guides.h
//
// What the reference forwarder exists for does not apply here and is deliberately absent: it is a
// module whose *path* contains "nvngx.dll", because NVIDIA's snippet resolves its caller's module and
// refuses anyone else. There is no snippet on this side and no caller gate. The file name is kept
// because it is what OptiScaler looks for, not because anything checks it.

#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <d3d12.h>

#include "nr_dlssnr_model.hpp"
#include "nr_ngx_abi.hpp"
#include "nr_pe_log.hpp"

extern "C" void nr_vk_load(void);   // generated by the build; see linux/build/build_optiscaler_nr.sh

using nr::pe::log;

namespace {

nr::dlssnr::Controls6 controls6(float intensity, int style, float localStructure, float localTone,
                                float skinStructure, int useAutoMask) {
    nr::dlssnr::Controls6 c;
    c.intensity = intensity;
    c.style = style;
    c.local_structure = localStructure;
    c.local_tone = localTone;
    c.skin_structure = skinStructure;
    c.use_auto_mask = useAutoMask;
    return c;
}

nr::dlssnr::Feature* as_feature(void* p) { return static_cast<nr::dlssnr::Feature*>(p); }

}  // namespace

extern "C" {

// ---------------------------------------------------------------------------------------------
// The float-slot dance.
//
// On NVIDIA this exists because the driver's own capability block does not keep floats where the
// public header says it does, so the host writes a probe value through each vtable slot in turn and
// keeps the one that round-trips. On this side the block is ours (linux/src/pe/nr_ngx_core.cpp), it is a
// plain implementation of the published interface, and floats are at MSVC's slot 6. The probe still
// has to work, because OptiScaler runs it unconditionally and logs an error if no slot answers.
// ---------------------------------------------------------------------------------------------

__declspec(dllexport) void dlssnr_call_set_float_slot(int slot) { nr::dlssnr::set_float_slot(slot); }

// Writes a float through an arbitrary vtable slot, so the host can find the right one by testing.
__declspec(dllexport) void dlssnr_call_probe_float(void* params, const char* name, float value,
                                                   int slot) {
    nr::dlssnr::probe_float(params, name, value, slot);
}

// Last init and create results, read by OptiScaler to say why a feature never appeared. NGX codes:
// 1 is NVSDK_NGX_Result_Success.
__declspec(dllexport) int dlssnr_call_last_init = 0;
__declspec(dllexport) int dlssnr_call_last_create = 0;

// Why the last create or evaluate declined, in words. OptiScaler copies this straight into the reason
// it shows the player (DlssNr_Dx12.cpp: g_nr.lastModelError). The reference answers from the snippet's
// NVFP4_GetLastError; ours answers from nr::pe::Session::status(), which is the same question -- the
// pointer stays valid until the next create or evaluate, which is as long as the caller needs it.
__declspec(dllexport) const char* dlssnr_call_error() { return nr::dlssnr::last_error(); }

__declspec(dllexport) int dlssnr_last_ratio_result = 0;
__declspec(dllexport) int dlssnr_last_ratio_stage = 0;

// ---------------------------------------------------------------------------------------------
// The model's own scaling ratio.
//
// NVIDIA's snippet may publish a DLSSNRComputeScalingRatioCallback into the capability block, which
// would say what resolution the model wants per quality level. Ours publishes nothing: the network is
// same-resolution by construction -- it enhances, it does not upscale -- so there is no ratio to
// report and it runs at whatever extent OptiScaler gives it.
//
// Returning 0 is the reference's "the callback was never published", which makes OptiScaler log
// "scaling ratio callback not published by this snippet (stage N)" and run at native resolution
// (DlssNr_Dx12.cpp ReportScalingRatios). Stage 1 means "the module was there and the block was
// valid", which is exactly the truth, and distinguishes this from a snippet that would not load.
// ---------------------------------------------------------------------------------------------
__declspec(dllexport) int dlssnr_query_scaling_ratio(const wchar_t* snippetPath, void* capabilityParams,
                                                     unsigned int perfQuality, float* outRatio) {
    (void) snippetPath;
    (void) perfQuality;
    dlssnr_last_ratio_result = 0;
    dlssnr_last_ratio_stage = (capabilityParams != nullptr && outRatio != nullptr) ? 1 : 0;
    return 0;
}

// ---------------------------------------------------------------------------------------------
// Native Direct3D 11.
//
// Not implemented, and reported as absent rather than broken. OptiScaler's D3D11 games reach the
// model through its Dx11-on-Dx12 bridge, which ends up in the D3D12 path below; a native D3D11 entry
// here would only duplicate that through DXVK interop, which Session::run_d3d11 already does for the
// game module and which nothing in OptiScaler calls.
//
// dlssnr_d3d11_probe returns a bit field of which entry points resolved: init 1, create 2, evaluate 4,
// release 8. Zero is "none of them", which is what the reference returns when the snippet exposes no
// D3D11 surface, and is what makes OptiScaler leave DlssNrProbeD3D11 reporting nothing and keep using
// the bridge.
// ---------------------------------------------------------------------------------------------
__declspec(dllexport) int dlssnr_d3d11_last_init = 0;
__declspec(dllexport) int dlssnr_d3d11_last_create = 0;

__declspec(dllexport) int dlssnr_d3d11_probe(const wchar_t* snippetPath) {
    (void) snippetPath;
    return 0;
}

// -2 is the reference's "the module would not load", i.e. the question cannot be answered here.
__declspec(dllexport) int dlssnr_d3d11_requirements(const wchar_t* snippetPath, void* adapter,
                                                    unsigned int* outFlags, unsigned int* outArch,
                                                    unsigned int* outOsVersion) {
    (void) snippetPath;
    (void) adapter;
    if (outFlags) *outFlags = 0;
    if (outArch) *outArch = 0;
    if (outOsVersion) *outOsVersion = 0;
    return -2;
}

__declspec(dllexport) int dlssnr_d3d11_init(const wchar_t* snippetPath, const wchar_t* dataPath,
                                            void* device, int sdkVersion, int* attemptOut,
                                            int* resultsOut) {
    (void) snippetPath;
    (void) dataPath;
    (void) device;
    (void) sdkVersion;
    if (attemptOut) *attemptOut = 0;
    // The reference writes -2 ("no such module") into each of its four attempt slots when nothing
    // could be loaded. Same shape, same length.
    if (resultsOut) for (int i = 0; i < 4; ++i) resultsOut[i] = -2;
    dlssnr_d3d11_last_init = static_cast<int>(NVSDK_NGX_Result_FAIL_NotImplemented);
    return dlssnr_d3d11_last_init;
}

__declspec(dllexport) void* dlssnr_d3d11_create(void* deviceContext, void* capabilityParams,
                                                unsigned int width, unsigned int height, int preset,
                                                float intensity, int style, float localStructure,
                                                float localTone, float skinStructure, int useAutoMask,
                                                int uiCorrection) {
    (void) deviceContext; (void) capabilityParams; (void) width; (void) height; (void) preset;
    (void) intensity; (void) style; (void) localStructure; (void) localTone; (void) skinStructure;
    (void) useAutoMask; (void) uiCorrection;
    dlssnr_d3d11_last_create = static_cast<int>(NVSDK_NGX_Result_FAIL_NotImplemented);
    return nullptr;
}

__declspec(dllexport) void dlssnr_d3d11_release(void* feature) { (void) feature; }

// ---------------------------------------------------------------------------------------------
// Vulkan.
// ---------------------------------------------------------------------------------------------

__declspec(dllexport) int dlssnr_vk_last_init = 0;
__declspec(dllexport) int dlssnr_vk_last_create = 0;

// The bit field OptiScaler reads to decide whether the native Vulkan path exists at all: init 1,
// create 2, evaluate 4, release 8. Fifteen, because all four are implemented here.
__declspec(dllexport) int dlssnr_vk_probe(const wchar_t* snippetPath) {
    (void) snippetPath;
    return 15;
}

__declspec(dllexport) int dlssnr_vk_init(const wchar_t* snippetPath, const wchar_t* dataPath,
                                         void* instance, void* physicalDevice, void* device,
                                         int sdkVersion) {
    (void) snippetPath;
    (void) dataPath;
    (void) sdkVersion;
    dlssnr_vk_last_init = nr::dlssnr::vk_init(instance, physicalDevice, device);
    return dlssnr_vk_last_init;
}

__declspec(dllexport) void* dlssnr_vk_create(void* cmdBuffer, void* capabilityParams, unsigned int width,
                                             unsigned int height, int preset, float intensity, int style,
                                             float localStructure, float localTone, float skinStructure,
                                             int useAutoMask, int uiCorrection) {
    return nr::dlssnr::create_vk(cmdBuffer, capabilityParams, width, height, preset, uiCorrection,
                                 controls6(intensity, style, localStructure, localTone, skinStructure,
                                           useAutoMask),
                                 &dlssnr_vk_last_create);
}

// Colour and output are at the working resolution; depth and motion come from the game's own upscaler
// call and may be at a different one, so each carries its own subrect and the caller has already
// scaled the motion vectors by the working/active ratio (DlssNr_Dx12.cpp: mvToWorkX = workWidth/width,
// passed as guideMvScaleX * mvToWorkX). The reference forwarder does not compute that ratio itself --
// it hands the number straight to DLSSNR.MVecScaleX -- and neither does this one.
__declspec(dllexport) int dlssnr_vk_evaluate_v2(void* cmdBuffer, void* feature, void* capabilityParams,
                                             void* color, void* depth, void* motion, void* output,
                                             unsigned int width, unsigned int height,
                                             unsigned int guideWidth, unsigned int guideHeight,
                                             unsigned int motionWidth, unsigned int motionHeight,
                                             unsigned int depthBaseX, unsigned int depthBaseY,
                                             unsigned int motionBaseX, unsigned int motionBaseY,
                                             int depthInverted, int reset, float intensity, int style,
                                             float localStructure, float localTone, float skinStructure,
                                             int useAutoMask, float mvScaleX, float mvScaleY) {
    const nr::dlssnr::Rect depth_rect{depthBaseX, depthBaseY, guideWidth, guideHeight};
    const nr::dlssnr::Rect motion_rect{motionBaseX, motionBaseY, motionWidth, motionHeight};
    return nr::dlssnr::evaluate_vk(cmdBuffer, as_feature(feature), capabilityParams, color, depth,
                                   motion, output, width, height, depth_rect, motion_rect,
                                   depthInverted, reset,
                                   controls6(intensity, style, localStructure, localTone,
                                             skinStructure, useAutoMask),
                                   mvScaleX, mvScaleY);
}

// The v1 evaluate, kept for a host built against the older ABI. v1 carried one guide extent and no
// origins, and its guideWidth/Height applied to depth and motion alike -- which is what passing them
// twice here says.
__declspec(dllexport) int dlssnr_vk_evaluate(void* cmdBuffer, void* feature, void* capabilityParams,
                                             void* color, void* depth, void* motion, void* output,
                                             unsigned int width, unsigned int height,
                                             unsigned int guideWidth, unsigned int guideHeight,
                                             int depthInverted, int reset, float intensity, int style,
                                             float localStructure, float localTone, float skinStructure,
                                             int useAutoMask, float mvScaleX, float mvScaleY) {
    return dlssnr_vk_evaluate_v2(cmdBuffer, feature, capabilityParams, color, depth, motion, output,
                                 width, height, guideWidth, guideHeight, guideWidth, guideHeight,
                                 0, 0, 0, 0, depthInverted, reset, intensity, style, localStructure,
                                 localTone, skinStructure, useAutoMask, mvScaleX, mvScaleY);
}

__declspec(dllexport) void dlssnr_vk_release(void* feature) { nr::dlssnr::release_vk(as_feature(feature)); }

// ---------------------------------------------------------------------------------------------
// Direct3D 12, through vkd3d-proton.
// ---------------------------------------------------------------------------------------------

__declspec(dllexport) void* dlssnr_call_create(const wchar_t* snippetPath, const wchar_t* dataPath,
                                               ID3D12Device* device, ID3D12GraphicsCommandList* cmd,
                                               void* capabilityParams, unsigned int width,
                                               unsigned int height, int preset, float intensity,
                                               int style, float localStructure, float localTone,
                                               float skinStructure, int useAutoMask,
                                               int uiCorrection) {
    (void) snippetPath;
    (void) dataPath;
    void* feature = nr::dlssnr::create_d3d12(device, cmd, capabilityParams, width, height, preset,
                                             uiCorrection,
                                             controls6(intensity, style, localStructure, localTone,
                                                       skinStructure, useAutoMask),
                                             &dlssnr_call_last_create);
    // The reference publishes both numbers and OptiScaler prints both; on this side there is no init
    // step separate from create, so they carry the same answer.
    dlssnr_call_last_init = dlssnr_call_last_create;
    return feature;
}

// Colour and output are at the working resolution; depth and motion come from the game's own upscaler
// call and may be at a different one, so each carries its own subrect base and extent, and the motion
// vectors arrive already scaled by the working/active ratio the caller computed
// (DlssNr_Dx12.cpp: guideMvScaleX * workWidth/width).
__declspec(dllexport) int dlssnr_call_evaluate_v2(ID3D12GraphicsCommandList* cmd, void* feature,
                                               void* capabilityParams, ID3D12Resource* color,
                                               ID3D12Resource* depth, ID3D12Resource* motion,
                                               ID3D12Resource* output, unsigned int width,
                                               unsigned int height, unsigned int guideWidth,
                                               unsigned int guideHeight, unsigned int motionWidth,
                                               unsigned int motionHeight, unsigned int depthBaseX,
                                               unsigned int depthBaseY, unsigned int motionBaseX,
                                               unsigned int motionBaseY, int depthInverted, int reset,
                                               float intensity, int style, float localStructure,
                                               float localTone, float skinStructure, int useAutoMask,
                                               float mvScaleX, float mvScaleY) {
    const nr::dlssnr::Rect depth_rect{depthBaseX, depthBaseY, guideWidth, guideHeight};
    const nr::dlssnr::Rect motion_rect{motionBaseX, motionBaseY, motionWidth, motionHeight};
    return nr::dlssnr::evaluate_d3d12(cmd, as_feature(feature), capabilityParams, color, depth, motion,
                                      output, width, height, depth_rect, motion_rect, depthInverted,
                                      reset,
                                      controls6(intensity, style, localStructure, localTone,
                                                skinStructure, useAutoMask),
                                      mvScaleX, mvScaleY);
}

// The v1 evaluate, kept for a host built against the older ABI -- which is what Dagherbou's release
// is. One guide extent, no origins, and it applied to depth and motion alike.
__declspec(dllexport) int dlssnr_call_evaluate(ID3D12GraphicsCommandList* cmd, void* feature,
                                               void* capabilityParams, ID3D12Resource* color,
                                               ID3D12Resource* depth, ID3D12Resource* motion,
                                               ID3D12Resource* output, unsigned int width,
                                               unsigned int height, unsigned int guideWidth,
                                               unsigned int guideHeight, int depthInverted, int reset,
                                               float intensity, int style, float localStructure,
                                               float localTone, float skinStructure, int useAutoMask,
                                               float mvScaleX, float mvScaleY) {
    return dlssnr_call_evaluate_v2(cmd, feature, capabilityParams, color, depth, motion, output, width,
                                   height, guideWidth, guideHeight, guideWidth, guideHeight, 0, 0, 0, 0,
                                   depthInverted, reset, intensity, style, localStructure, localTone,
                                   skinStructure, useAutoMask, mvScaleX, mvScaleY);
}

// The extras NVIDIA's Streamline plugin sets and the positional exports predate.
//
// globalTone is inert. It is inert in the reference too -- DLSSNR.GlobalToneStrength is not one of the
// snippet's 61 DLSSNR.* names (the pre-SR fork's own DlssNr_Common.h:315-320 says so and leaves the
// constant commented out), so every write went into a map nothing read -- and it is inert here for
// the stronger reason that our network has no such control: nr::Controls carries local_tone, which is
// a different thing and arrives through evaluate. Kept in the signature so the ABI does not churn.
//
// The UI layer, its alpha and the back buffer are accepted and dropped. Our network has no UI
// correction pass, so there is nothing to give them to; OptiScaler always passes nulls here anyway
// (DlssNr_Dx12.cpp: SetExtras(cfg, nullptr, nullptr, 0, 0, 0, 0)).
__declspec(dllexport) void dlssnr_call_set_extras(void* capabilityParams, float globalTone,
                                                  ID3D12Resource* ui, ID3D12Resource* uiAlpha,
                                                  ID3D12Resource* backbuffer, unsigned int uiWidth,
                                                  unsigned int uiHeight, unsigned int bbWidth,
                                                  unsigned int bbHeight) {
    (void) capabilityParams;
    (void) globalTone;
    (void) ui;
    (void) uiAlpha;
    (void) backbuffer;
    (void) uiWidth;
    (void) uiHeight;
    (void) bbWidth;
    (void) bbHeight;
}

__declspec(dllexport) void dlssnr_call_release(void* feature) {
    nr::dlssnr::release_d3d12(as_feature(feature));
}

}  // extern "C"

BOOL APIENTRY DllMain(HMODULE module, DWORD reason, LPVOID reserved) {
    (void) reserved;
    if (reason == DLL_PROCESS_ATTACH) {
        DisableThreadLibraryCalls(module);
        nr::pe::set_module(module);
        nr_vk_load();
        log("[nr] nvngx.dll_dlssnr.dll attached, log %s", nr::pe::log_path());
    }
    return TRUE;
}
